services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mytrip-backend
    container_name: mytrip-backend
    ports:
      - "80:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: sql7.freemysqlhosting.net
      DB_PORT: 3306
      DB_DATABASE: sql7734510
      DB_USERNAME: sql7734510
      DB_PASSWORD: caSahQDLZd

  php-apache:
    image: php:apache
    container_name: mytrip-php-apache
    volumes:
      - .:/var/www/html

volumes:
  db_data:
