services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mytrip-backend
    container_name: mytrip-backend
    ports:
      - "8080:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: sql7.freemysqlhosting.net
      DB_PORT: 3306
      DB_DATABASE: sql7734510
      DB_USERNAME: sql7734510
      DB_PASSWORD: caSahQDLZd

  php-fpm:
    image: php:fpm
    container_name: mytrip-php-fpm
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx
    container_name: mytrip-nginx
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - .:/var/www/html
    depends_on:
      - app
      - php-fpm

volumes:
  db_data:
