services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mytrip-backend
    container_name: mytrip-backend
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mydatabase
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:5.7
    container_name: mytrip-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  php-fpm:
    image: php:fpm
    container_name: mytrip-php-fpm
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx
    container_name: mytrip-nginx
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - .:/var/www/html
    depends_on:
      - app
      - php-fpm

volumes:
  db_data:
