services:
  - type: web
    name: MyTrips
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        sync: base64:NEvPLMuuxdTboXxRQ9HIYNag0AFTa1rgmMHTFaqVs3E=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql7.freemysqlhosting.net
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: sql7734510
      - key: DB_USERNAME
        value: sql7734510
      - key: DB_PASSWORD
        value: caSahQDLZd
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "apache2-foreground"
